[build]
command = "npm run build"  # If you have a build step
publish = "dist"           # Directory where your built files are located

[dev]
command = "npm start"      # Start command for local development
