[build]
  command = "npm run build"  # Your build command
  publish = "dist"           # Directory where your built files are located

[dev]
  command = "npm start"      # Start command for local development
